#include <stddef.h>
#include <string.h>
#include "http.h"

static const char* http_mime_type_extensions[79] = {
    ".aac", ".abw", ".apng", ".arc", ".avif", ".avi", ".azw", ".bin", ".bmp", ".bz", 
    ".bz2", ".cda", ".csh", ".css", ".csv", ".doc", ".docx", ".eot", ".epub", ".gz",
    ".gif", ".htm", ".html", ".ico", ".ics", ".jar", ".jpeg", ".jpg", ".js", ".json", 
    ".jsonld", ".md", ".mid", ".midi", ".mjs", ".mp3", ".mp4", ".mpeg", ".mpkg", ".odp",
    ".ods", ".odt", ".oga", ".ogv", ".ogx", ".opus", ".otf", ".png", ".pdf", ".php",
    ".ppt", ".pptx", ".rar", ".rtf", ".sh", ".svg", ".tif", ".tiff", ".ts", ".ttf", 
    ".txt", ".vsd", ".wav", ".weba", ".webm", ".webmanifest", ".webp", ".woff", ".woff2", 
    ".xhtml", ".xls", ".xlsx", ".xml", ".xul", ".zip", ".3gp", ".3g2", ".7z"
};

static const char* http_mime_type_strings[79] = {
    "audio/aac", 
    "application/x-abiword", 
    "image/apng", 
    "application/x-freearc", 
    "image/avif", 
    "video/x-msvideo", 
    "application/vnd.amazon.ebook", 
    "application/octet-stream",
    "image/bmp",
    "application/x-bzip",
    "application/x-bzip2",
    "application/x-cdf",
    "application/x-csh",
    "text/css",
    "text/csv",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-fontobject",
    "application/epub+zip",
    "application/gzip",
    "image/gif",
    "text/html",
    "text/html",
    "image/vnd.microsoft.icon",
    "text/calendar",
    "application/java-archive",
    "image/jpeg",
    "image/jpeg",
    "text/javascript",
    "application/json",
    "application/ld+json",
    "text/markdown",
    "audio/midi",
    "audio/x-midi",
    "text/javascript",
    "audio/mpeg",
    "video/mp4",
    "video/mpeg",
    "application/vnd.apple.installer+xml",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.text",
    "audio/ogg",
    "video/ogg",
    "application/ogg",
    "audio/ogg",
    "font/otf",
    "image/png",
    "application/pdf",
    "application/x-httpd-php",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.rar",
    "application/rtf",
    "application/x-sh",
    "image/svg+xml",
    "application/x-tar",
    "image/tiff",
    "image/tiff",
    "video/mp2t",
    "font/ttf",
    "text/plain",
    "application/vnd.visio",
    "audio/wav",
    "audio/webm",
    "video/webm",
    "application/manifest+json",
    "image/webp",
    "font/woff",
    "font/woff2",
    "application/xhtml+xml",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/xml",
    "application/vnd.mozilla.xul+xml",
    "application/zip",
    "video/3gpp",
    "video/3gpp2",
    "application/x-7z-compressed",
};

const char* http_getMIMEtype(const char* file) {
    const char* ext = http_get_filename_ext(file);
    for (int i = 0; i < (sizeof(http_mime_type_extensions)/sizeof(http_mime_type_extensions[0])); i++)
        if (strcmp(ext, http_mime_type_extensions[i]) == 0) return http_mime_type_strings[i];
    return NULL;
}